#!/usr/bin/env python3
"""
Write report/generated_quantities.tex from output/lambda_max.csv and output/empirical_thresholds.csv.

Run after aggregate_thresholds (or with stale/missing CSVs: writes safe fallbacks matching the last
known single-seed baseline so LaTeX still compiles).

Usage (from project root):
  py -3 scripts/write_report_macros.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
OUT_LAM = ROOT / "output" / "lambda_max.csv"
OUT_EMP = ROOT / "output" / "empirical_thresholds.csv"
DEST = ROOT / "report" / "generated_quantities.tex"

PRIMARY_SEED = 10001
EW = 5.0
BETA_GRID_MAX = 0.048

# Fallbacks if CSVs missing (previous single-seed run)
_FALLBACK = {
    "lambda_max": 7.181,
    "num_edges": 5979,
    "k_mean": 5.979,
    "k2_mean": 24.95,
    "beta_pred": 0.0278527163754995,
    "rows": [
        ("exponential", 0.048, 0.048, 0.048, 1.723, 8.0),
        ("lognormal (Tang)", 0.048, 0.048, 0.048, 1.723, 9.0),
        ("power law (Tang)", 0.044, 0.044, 0.044, 1.580, 15.0),
    ],
}
_FB_BY_REG = {r[0]: r[1:] for r in _FALLBACK["rows"]}


def _fmt(x: float, d: int = 4) -> str:
    s = f"{float(x):.{d}f}"
    if "." in s:
        s = s.rstrip("0").rstrip(".")
    return s


def _load_lambda() -> dict:
    if not OUT_LAM.is_file():
        return {k: v for k, v in _FALLBACK.items() if k != "rows"}
    lam = pd.read_csv(OUT_LAM)
    er = lam[(lam["net_label"].astype(str) == "ER") & (lam["random_seed"].astype(int) == PRIMARY_SEED)]
    if er.empty:
        er = lam[lam["net_label"].astype(str) == "ER"]
    if er.empty:
        return {k: v for k, v in _FALLBACK.items() if k != "rows"}
    row = er.iloc[0]
    lm = float(row["lambda_max"])
    ne = int(row["num_edges"]) if "num_edges" in row and pd.notna(row["num_edges"]) else _FALLBACK["num_edges"]
    k1 = float(row["k_mean"]) if "k_mean" in row and pd.notna(row["k_mean"]) else _FALLBACK["k_mean"]
    k2 = float(row["k2_mean"]) if "k2_mean" in row and pd.notna(row["k2_mean"]) else _FALLBACK["k2_mean"]
    bp = 1.0 / (lm * EW)
    return {"lambda_max": lm, "num_edges": ne, "k_mean": k1, "k2_mean": k2, "beta_pred": bp}


def _load_empirical(beta_pred: float) -> list[tuple[str, float, float, float, float, float]]:
    """Return list of (regime_key, beta_hat, ci_lo, ci_hi, ratio, med_ext)."""
    keys = ["exponential", "lognormal (Tang)", "power law (Tang)"]
    if not OUT_EMP.is_file():
        return [(k, *_FB_BY_REG[k]) for k in keys]
    emp = pd.read_csv(OUT_EMP)
    emp = emp[(emp["net_label"].astype(str) == "ER") & (emp["random_seed"].astype(int) == PRIMARY_SEED)]
    out: list[tuple[str, float, float, float, float, float]] = []
    for k in keys:
        sub = emp[emp["recovery_regime"].astype(str).str.lower() == k.lower()]
        if sub.empty:
            out.append((k, *_FB_BY_REG[k]))
            continue
        r = sub.iloc[0]
        bh = float(r["beta_hat_surv_50"])
        lo = float(r["beta_hat_surv_50_ci_low"])
        hi = float(r["beta_hat_surv_50_ci_high"])
        ratio = float(r["ratio_surv_50_over_pred"]) if np.isfinite(r["ratio_surv_50_over_pred"]) else bh / beta_pred
        med = float(r["median_tick_if_extinct"])
        out.append((k, bh, lo, hi, ratio, med))
    return out


def main() -> None:
    L = _load_lambda()
    lm = L["lambda_max"]
    beta_pred = float(L["beta_pred"])
    tau_pred = beta_pred * EW
    k1, k2 = L["k_mean"], L["k2_mean"]
    tau_het = k1 / k2 if k2 > 0 else np.nan
    beta_het = tau_het / EW if np.isfinite(tau_het) else np.nan
    pct_het = 100.0 * (beta_het - beta_pred) / beta_pred if beta_pred > 0 and np.isfinite(beta_het) else 3.0

    rows = _load_empirical(beta_pred)
    ratios = [r[4] for r in rows]
    cmin, cmax = min(ratios), max(ratios)

    lines = [
        "% -*- latex -*-",
        "% Generated by scripts/write_report_macros.py — do not edit by hand.",
        f"\\newcommand{{\\RepPrimarySeed}}{{{PRIMARY_SEED}}}",
        f"\\newcommand{{\\RepNumNodes}}{{2000}}",
        f"\\newcommand{{\\RepNumEdges}}{{{L['num_edges']}}}",
        f"\\newcommand{{\\RepKmean}}{{{_fmt(k1, 3)}}}",
        f"\\newcommand{{\\RepLambdaMax}}{{{_fmt(lm, 3)}}}",
        f"\\newcommand{{\\RepBetaPred}}{{{_fmt(beta_pred, 7)}}}",
        f"\\newcommand{{\\RepTauPred}}{{{_fmt(tau_pred, 4)}}}",
        f"\\newcommand{{\\RepTauHet}}{{{_fmt(tau_het, 3)}}}",
        f"\\newcommand{{\\RepBetaHet}}{{{_fmt(beta_het, 4)}}}",
        f"\\newcommand{{\\RepBetaHetPctAbove}}{{{_fmt(pct_het, 1)}}}",
        f"\\newcommand{{\\RepBetaGridMax}}{{{_fmt(BETA_GRID_MAX, 3)}}}",
        f"\\newcommand{{\\RepCeffMin}}{{{_fmt(cmin, 3)}}}",
        f"\\newcommand{{\\RepCeffMax}}{{{_fmt(cmax, 3)}}}",
    ]

    suffix = ["Exp", "Logn", "PL"]
    for suf, r in zip(suffix, rows):
        _, bh, lo, hi, ratio, med = r
        lines.append(f"\\newcommand{{\\RepTh{suf}Hat}}{{{_fmt(bh, 3)}}}")
        lines.append(f"\\newcommand{{\\RepTh{suf}Lo}}{{{_fmt(lo, 3)}}}")
        lines.append(f"\\newcommand{{\\RepTh{suf}Hi}}{{{_fmt(hi, 3)}}}")
        lines.append(f"\\newcommand{{\\RepTh{suf}Ratio}}{{{_fmt(ratio, 3)}}}")
        lines.append(f"\\newcommand{{\\RepTh{suf}MedExt}}{{{_fmt(med, 0)}}}")

    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("Wrote", DEST)


if __name__ == "__main__":
    main()
    sys.exit(0)
